---
abstract: 'Proposal: The Decentralised Active Threat Network'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: ThreatNet::DATN2004
name: ThreatNet-DATN2004
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.005
version: 0.20
